
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xfeedforward.h"

/*
* The configuration table for devices
*/

XFeedforward_Config XFeedforward_ConfigTable[XPAR_XFEEDFORWARD_NUM_INSTANCES] =
{
	{
		XPAR_FEEDFORWARD_0_DEVICE_ID,
		XPAR_FEEDFORWARD_0_S_AXI_CTRL_BUS_BASEADDR
	}
};


