#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jan 31 16:35:20 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 floating_point_v7_1_11 blk_mem_gen_v8_4_4 axi_bram_ctrl_v4_1_4 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 lib_pkg_v1_0_2 axi_timer_v2_0_24 proc_sys_reset_v5_0_13 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/jakub/apps/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_11 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/b0c0/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work floating_point_v7_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/b0c0/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_b1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_CTRL_BUS_s_axi.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_fadd_32ns_32ns_32_5_full_dsp_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_fcmp_32ns_32ns_1_2_no_dsp_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_fdiv_32ns_32ns_32_16_no_dsp_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_fexp_32ns_32ns_32_9_full_dsp_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_fmul_32ns_32ns_32_4_max_dsp_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_l1y.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_0.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_1.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_2.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_3.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_4.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_5.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_6.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_7.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_8.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_9.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_10.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_11.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_12.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_13.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_14.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w1_15.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_w2_0.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward_wy_sum.vhd" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/vhdl/feedforward.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/ip/feedforward_ap_fadd_3_full_dsp_32.v" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/ip/feedforward_ap_fexp_7_full_dsp_32.v" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/ip/feedforward_ap_fdiv_14_no_dsp_32.v" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/ip/feedforward_ap_fmul_2_max_dsp_32.v" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/595b/hdl/ip/feedforward_ap_fcmp_0_no_dsp_32.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_feedforward_0_0/sim/design_1_feedforward_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_blk_mem_gen_0_1/sim/design_1_blk_mem_gen_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_4 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/c9f0/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_1/sim/design_1_axi_bram_ctrl_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/70d6/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_timer_0_0/sim/design_1_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_50M_0/sim/design_1_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../neural_network_vivado_ar.gen/sources_1/bd/design_1/ipshared/34f8/hdl" +incdir+"/home/jakub/apps/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
